### ISSUE TITLE
Tanya

### ISSUE THREAD

**Issue by bagussatoto** [binsarjr/amikomtwo#1]
> # Izin Bertanya Bang Binsar
 
- [x] Apa saja fitur didalam aplikasi website tersebut?
- [x] Apakah aplikasi ini bisa dibuat secara massal ?

> ## Terimakasih. <br> Mohon maaf baru pemula

**Comment by binsarjr** [comment]
Saat ini fitur yang ada baru presensi cepat,yaitu presensi menggunakan qrcode dan bisa menyimpan banyak nim.

Terkait aplikasi bisa dibuat massal ini maksudnya bagaimana yah? code ini di clone terus dibuat domain baru atau aplikasi ini dipakai oleh banyak pengguna?

dua dua nya bisa dalam batas wajar. untuk penggunaan user saya rasa dalam beberapa kasus mngkin akan terjadi error dikarenakan kita menggunakan vercel sebagai serverless function.

Ini akan jadi tugas berikutnya untuk mencoba menerapkan software arsitechture service discovery atau semacamnya (untuk saat ini karena belum dibutuhkan akan dilewatkan dulu)

**Comment by bagussatoto** [comment]
**Terimakasih atas jawabannya opsi 1.**

opsi 2 hanya saya sudah jelas ternyata.
saya kira opsi 2 itu menyangkut adanya privasi dalam pembuatan. 

sukses kedepannya untuk penambahan fitur lagi.

**Comment by binsarjr** [comment]
Oh tidak ada. ini akan full open source
